Update v1-candidate branch refs (v1-candidate)
canonical/microcloud-pkg-snap pull request #40
Opened 2024-12-12 16:50 UTC by masnax

2024-12-12 16:53 UTC, roosterfish approved these changes, later dismissed

2024-12-13 09:55 UTC, roosterfish requested changes

2024-12-13 09:55 UTC, roosterfish commented on README.md
> +* [`2/candidate`](https://launchpad.net/~microcloud-admins/microcloud/+snap/microcloud-v2-candidate)
`microcloud-snap`?

2024-12-13 15:04 UTC, tomponline commented on README.md
> +* [`2/candidate`](https://launchpad.net/~microcloud-admins/microcloud/+snap/microcloud-v2-candidate)
yeah good spot

2024-12-13 16:03 UTC, masnax commented on README.md
> +* [`2/candidate`](https://launchpad.net/~microcloud-admins/microcloud/+snap/microcloud-v2-candidate)
Fixed

2024-12-13 16:05 UTC, roosterfish approved these changes

2024-12-13 16:07 UTC, merged